### ISSUE TITLE
can't parser the hostheader 

### ISSUE THREAD

**Issue by PromiseNoDieForever** [Sentinel-One/CobaltStrikeParser#24]
https://www.virustotal.com/gui/file/d11b0bd9c3513f4634127b6c54a51f4a613b499dc1f75f8c7bd906b26f6d711b?nocache=1  

![1](https://user-images.githubusercontent.com/74523139/220113372-1198c4e1-47b4-4f1d-8606-6b09c46c4c72.png)

**Comment by PromiseNoDieForever** [comment]
![image](https://user-images.githubusercontent.com/74523139/220113710-00b363f7-e03e-4dd8-a747-fd7d382dd9f9.png)

**Comment by Kristal-g** [comment]
Thanks for the feedback!
In this case it's parsed as part of the HTTP Requests metadata; that's how the attacker chose to configure the HOST header for the payload..
![image](https://user-images.githubusercontent.com/61376744/220128946-93e90166-0199-4139-bd24-e309ffdf8391.png)
