### ISSUE TITLE
Does it works with updated CS version?

### ISSUE THREAD

**Issue by kartone** [Sentinel-One/CobaltStrikeParser#3]
It's unable to parse CS v4 configuration. Is this issue depend on START_PATTERN variable that needs to be updated?

**Comment by Kristal-g** [comment]
I'll need to look at the binary, if you're willing to share it.

**Comment by kartone** [comment]
Update: it works on memory dump and on process dump but not on the executable itself.

**Comment by lazydaemon** [comment]
The parser does not work for this beacon:
https://www.virustotal.com/gui/file/09826a26914844890c8d15b154a557786f1f195452a93eeaba688de9f669b1ee/detection

The XOR key for this sample is [0xBF, 0x1F, 0xB3, 0x1C], see the attached screenshot before and after decryption
<img width="635" alt="before" src="https://user-images.githubusercontent.com/3420941/96579159-afffa480-12d6-11eb-89ce-6ad90b265899.png">
<img width="647" alt="after" src="https://user-images.githubusercontent.com/3420941/96579142-a9712d00-12d6-11eb-95b6-0c780ae2683b.png">

**Comment by Kristal-g** [comment]
Hey, this is only a stager and does not contain the beacon itself.
In this case, download the beacon from the embedded URL and then test the script on it 👍

**Comment by nembo81** [comment]
Hi there, please check this sample : https://www.virustotal.com/gui/file/b1eb36e00c901d7f6de50f39eb948df12fcba967afec9c60d4df619c71125089/detection
It should be a staged one (v4) and it's not recognised by the script.
