### ISSUE TITLE
error line 38

### ISSUE THREAD

**Issue by NomisRenarc** [Sentinel-One/CobaltStrikeParser#8]
Hi all,

I am trying to use this parser and it is erroring with the following:

 File "parse_beacon_config.py", line 38
    print(msg, end=end)
                  ^
Please advise as to a fix, as I am unsure on what to try change at the moment. Any assistance will be greatly appreciated, and hope I can help contribute to at same stage.

**Comment by Kristal-g** [comment]
What is the error?
Maybe you're using python2 instead of python3?

**Comment by NomisRenarc** [comment]
> What is the error?
> Maybe you're using python2 instead of python3?

sorry I cannot believe I didn't launch as python3. If I am to target a memory dump directly, would the path field just be the memory capture file?

**Comment by Kristal-g** [comment]
Yes, just try it :)

**Comment by NomisRenarc** [comment]
> Yes, just try it :)

if I try it like this:

parse_beacon_config.py --json test-memory-dump.img

it runs for a few seconds and returns the state:

Killed

does the memory dump need to be in a specific format then?
